@startuml Diagrama

class Proponente{
    -Exp
}

class DEU_CE{

}

class CE{

}

class DE{

}

CE --|> DEU_CE
DE --|> DEU_CE

CE -- Formulacion_Curso : Verificacion
DE -- Formulacion_Curso : Verificacion

class Persona_Natural{
    -CI
    -RIF
    -Resumen_Curricular
    -Copia_de_titulo

}

class Persona_Juridica{
    -Registro_Mercantil
    -CI_Representante_legal
    -RIF
    -Resumen_Curricular
    -Copia_de_titulo
}

class Registro{
}

class Persona{
    -Datos_Personales
}

Registro -- Persona
Registro --> Persona_Juridica
Registro --> Persona_Natural

Persona_Juridica --> Proponente
Persona_Natural --> Proponente

class Formulacion_Curso{
    -Denominacion
    -Objetivos
    -Fundamentacion
    -Perfiles_I_E
    -Perfil_Docente
    -Estructura_Curricular
    -Estrategias_Evaluacion
    -Exigencias_Y_Servicios
    -Duracion
    -Estructura_Costo
    -Cronograma_De_Ejecucion
}

Proponente --> Formulacion_Curso : Llena


@enduml