/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.BD_Control;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import javax.swing.table.DefaultTableModel;
import modelo.Curso;
import modelo.Proponente;
import vista.CursoDetalladoView;
import controlador.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Mattxx
 */
public class CursosView extends javax.swing.JFrame {

    /**
     * Creates new form CursosView
     */
    public CursosView() {
        initComponents();
        int c = 1;
        LlenarTable(c);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));

        jButton3.setBackground(new java.awt.Color(217, 217, 217));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Img/curseate-logo.png"))); // NOI18N
        jButton3.setText("jButton3");

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel6.setText("Página Principal");

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 3, 48)); // NOI18N
        jLabel7.setText("Curseate");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(931, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(41, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addContainerGap()))
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..:: Curseate - Gestionar Cursos ::..");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(86, 81, 81));

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));

        jButton4.setBackground(new java.awt.Color(217, 217, 217));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Img/curseate-logo.png"))); // NOI18N
        jButton4.setText("jButton3");
        jButton4.setBorder(null);

        jLabel27.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel27.setText("Curseate ");

        jLabel26.setFont(new java.awt.Font("Monotype Corsiva", 1, 32)); // NOI18N
        jLabel26.setText("Cursos | Admin");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel27)
                .addGap(19, 19, 19))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel1.setText("Tabla de Cursos");

        jScrollPane1.setBackground(new java.awt.Color(217, 217, 217));

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(217, 217, 217), 1, true));
        jTable1.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(217, 217, 217));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Indice", "Nombre del Curso", "Duración", "Proponente", "Estado Aprobación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setSelectionBackground(new java.awt.Color(86, 81, 81));
        jTable1.setSelectionForeground(new java.awt.Color(217, 217, 217));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1074, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jButton9.setBackground(new java.awt.Color(86, 81, 81));
        jButton9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setLabel("Volver a Home");
        jButton9.setPreferredSize(new java.awt.Dimension(103, 23));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9jButton1ActionPerformed
        UI_Home_Admin homeFrame = new UI_Home_Admin();
        homeFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9jButton1ActionPerformed

     private void LlenarTable(int c) {
        
        BD_Control DB = BD_Control.getinstancia();
        ArrayList<Proponente> Proponentes= DB.getProponentes();
        DefaultTableModel dt = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int col) {
                return false;
            }
        };
        dt.addColumn("Indice");
        dt.addColumn("Nombre del Curso");
        dt.addColumn("Duración");
        dt.addColumn("Proponente");
        dt.addColumn("Estado Aprobación");
        
        
        for (Proponente Proponente : Proponentes) {
            
            ArrayList<Curso> Cursos = Proponente.getCursos();
            if(!Cursos.isEmpty()){
                for(Curso curso : Cursos){
                    Object p[] = new Object[5];
                    p[0]= c;
                    p[1]=curso.getFormulario().getDenominacion();
                    p[2]=curso.getFormulario().getDuracion();
                    p[3]=Proponente.getNombre();
                    p[4]=curso.getEstado();
                    dt.addRow(p);
                    curso.setIndice(c);
                    c++;
                } 
                c = 1;
            } 
        }
        jTable1.setModel(dt);
       
        JPopupMenu pop = new JPopupMenu();
        JMenuItem menu1 = new JMenuItem("Aprobar Propuesta Curso");
        JMenuItem menu2 = new JMenuItem("Poner curso en espera");
        JMenuItem menu3 = new JMenuItem("Rechazar Propuesta Curso");
        JMenuItem menu4 = new JMenuItem("Ver Curso Detallado");
        pop.add(menu1);
        pop.add(menu2);
        pop.add(menu3);
        pop.add(menu4);
        jTable1.setComponentPopupMenu(pop);
        CursosView thisframe = this;
        menu1.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultTableModel modelo= (DefaultTableModel)jTable1.getModel();
                Object p = "Aprobado";
                modelo.setValueAt(p,jTable1.getSelectedRow(), 4);
                jTable1.setModel(modelo);
                String nombreCurso= modelo.getValueAt(jTable1.getSelectedRow(), 1).toString();
                String nombre= modelo.getValueAt(jTable1.getSelectedRow(), 3).toString();
                for (Proponente Proponente : Proponentes) {
                    ArrayList<Curso> Cursos = Proponente.getCursos();
                    for(Curso curso : Cursos){
                        if(Proponente.getNombre().equals(nombre) && curso.getFormulario().getDenominacion().equals(nombreCurso)){
                            curso.setEstado(true); 
                            String carta = JOptionPane.showInputDialog("Enviar carta de intención");
                            Proponente_Control proponente = Proponente_Control.getinstancia();
                            Factory_Cartas intencion = new Factory_Cartas_intencion();
                            intencion.Subir_Carta(carta);
                            DB.guardarTxt();
                            JOptionPane.showMessageDialog(thisframe, "Carta de intención enviada" );
                            menu1.setEnabled(false);
                        }
                    }
                    
                } 
            }
            
            }
        );
        
        menu2.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultTableModel modelo= (DefaultTableModel)jTable1.getModel();
                Object p = "En Espera";
                modelo.setValueAt(p,jTable1.getSelectedRow(), 4);
                jTable1.setModel(modelo);
                String nombreCurso= modelo.getValueAt(jTable1.getSelectedRow(), 1).toString();
                String nombre= modelo.getValueAt(jTable1.getSelectedRow(), 3).toString();
                for (Proponente Proponente : Proponentes) {
                    ArrayList<Curso> Cursos = Proponente.getCursos();
                    for(Curso curso : Cursos){
                        if(Proponente.getNombre().equals(nombre) && curso.getFormulario().getDenominacion().equals(nombreCurso)){
                            
                            curso.setEstado(false); DB.guardarTxt();
                           JOptionPane.showMessageDialog(thisframe, "Propuesta de Curso en espera" );
                           menu2.setEnabled(false);
                        }
                    }
                    
                }
            }
            
            }
        );
        
        menu3.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultTableModel modelo= (DefaultTableModel)jTable1.getModel();
                Object p = "Rechazado";
                modelo.setValueAt(p,jTable1.getSelectedRow(), 4);
                jTable1.setModel(modelo);
                String nombreCurso= modelo.getValueAt(jTable1.getSelectedRow(), 1).toString();
                String nombre= modelo.getValueAt(jTable1.getSelectedRow(), 3).toString();
                for (Proponente Proponente : Proponentes) {
                    ArrayList<Curso> Cursos = Proponente.getCursos();
                    for(Curso curso : Cursos){
                        if(Proponente.getNombre().equals(nombre) && curso.getFormulario().getDenominacion().equals(nombreCurso)){
                            
                            curso.setEstado(true); 
                            String carta = JOptionPane.showInputDialog("Enviar carta de rechazo");
                            Proponente_Control proponente = Proponente_Control.getinstancia();
                            Factory_Cartas intencion = new Factory_Cartas_Rechazo();
                            intencion.Subir_Carta(carta);
                            DB.guardarTxt();
                            JOptionPane.showMessageDialog(thisframe, "Carta de rechazo enviada" );
                            menu3.setEnabled(false);
                        }
                    }
                    
                }
            }
            
            }
        );
        
        menu4.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultTableModel modelo= (DefaultTableModel)jTable1.getModel();
                if(jTable1.getSelectedRow()>=0){
                    String nombreCurso= modelo.getValueAt(jTable1.getSelectedRow(), 1).toString();
                String nombre= modelo.getValueAt(jTable1.getSelectedRow(), 3).toString();
                String c = modelo.getValueAt(jTable1.getSelectedRow(), 0).toString();
               
                int indiceC = Integer.parseInt(c);
                for (Proponente Proponente : Proponentes) {
                    ArrayList<Curso> Cursos = Proponente.getCursos();
                    for(Curso curso : Cursos){
                        if( Proponente.getNombre().equals(nombre) && curso.getFormulario().getDenominacion().equals(nombreCurso)){
                        Proponente_Control P1 = Proponente_Control.getinstancia();
                        P1.setProponente(Proponente);
                        Curso_Control c1 = Curso_Control.getinstancia();
                        c1.CursoSelect(indiceC,Proponente.getNombre(),Proponente.getPassword());
                        CursoDetalladoView frame = new CursoDetalladoView();
                        frame.setVisible(true);
                        thisframe.dispose();
                        }
                    }
                    
                }
                }
                
            }
            
            }
        );
        
    } 
    
     
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursosView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
