/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Proponente_Control;
import java.io.IOException;
import java.net.URISyntaxException;
import java.awt.*;
import javax.swing.JOptionPane;
import controlador.*;
import modelo.*;
import java.util.ArrayList;
/**
 *
 * @author emili
 */
public class CursoDetalladoView extends javax.swing.JFrame {

    /**
     * Creates new form ProponerView
     */
    public CursoDetalladoView() {
        initComponents();
        this.setSize(1280,720);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.getContentPane().setBackground(new java.awt.Color(86,81,81));
        rechazoLabel.setVisible(false);
        carta.setVisible(false);
        jButton3.setVisible(false);
        Aprobar2.setVisible(false);
        mostrar_curso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Objetivos = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Fundamentacion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        Perfil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        carta = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Estructura_Costo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Cronograma = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Estructura_Curricular = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Estrategia_Evaluacion = new javax.swing.JTextField();
        Duracion = new javax.swing.JTextField();
        Denominacion = new javax.swing.JTextField();
        Perfil_Docente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Titulo = new javax.swing.JTextField();
        Datos = new javax.swing.JLabel();
        Enespera = new javax.swing.JButton();
        Aprobar = new javax.swing.JButton();
        Rechazar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        rechazoLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Exigencias = new javax.swing.JTextArea();
        Aprobar2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("..:: Curseate - Gestión de Curso ::..");

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 100));

        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel12.setText("Formulario");

        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 48)); // NOI18N
        jLabel13.setText("Curseate");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Img/curseate-logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 714, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 400));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel2.setText("Dominacion");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel3.setText("Objetivos");

        Objetivos.setBackground(new java.awt.Color(86, 81, 81));
        Objetivos.setColumns(20);
        Objetivos.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Objetivos.setForeground(new java.awt.Color(255, 255, 255));
        Objetivos.setLineWrap(true);
        Objetivos.setRows(5);
        Objetivos.setWrapStyleWord(true);
        Objetivos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(Objetivos);

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel4.setText("Fundamentacion");

        Fundamentacion.setBackground(new java.awt.Color(86, 81, 81));
        Fundamentacion.setColumns(20);
        Fundamentacion.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Fundamentacion.setForeground(new java.awt.Color(255, 255, 255));
        Fundamentacion.setLineWrap(true);
        Fundamentacion.setRows(5);
        Fundamentacion.setWrapStyleWord(true);
        Fundamentacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setViewportView(Fundamentacion);

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel5.setText("Perfil de Ingreso o Egreso");

        Perfil.setBackground(new java.awt.Color(86, 81, 81));
        Perfil.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Perfil.setForeground(new java.awt.Color(255, 255, 255));
        Perfil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel6.setText("Exigencias");

        carta.setBackground(new java.awt.Color(86, 81, 81));
        carta.setColumns(20);
        carta.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        carta.setForeground(new java.awt.Color(255, 255, 255));
        carta.setLineWrap(true);
        carta.setRows(5);
        carta.setWrapStyleWord(true);
        carta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        carta.setDisabledTextColor(new java.awt.Color(217, 217, 217));
        jScrollPane3.setViewportView(carta);

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setText("Duracion");

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setText("Estructura de Costo");

        Estructura_Costo.setBackground(new java.awt.Color(86, 81, 81));
        Estructura_Costo.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Estructura_Costo.setForeground(new java.awt.Color(255, 255, 255));
        Estructura_Costo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel9.setText("Cronograma");

        Cronograma.setBackground(new java.awt.Color(86, 81, 81));
        Cronograma.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Cronograma.setForeground(new java.awt.Color(255, 255, 255));
        Cronograma.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel10.setText("Estructura Curricular");

        Estructura_Curricular.setBackground(new java.awt.Color(86, 81, 81));
        Estructura_Curricular.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Estructura_Curricular.setForeground(new java.awt.Color(255, 255, 255));
        Estructura_Curricular.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel11.setText("Estrategia de Evaluacion");

        Estrategia_Evaluacion.setBackground(new java.awt.Color(86, 81, 81));
        Estrategia_Evaluacion.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Estrategia_Evaluacion.setForeground(new java.awt.Color(255, 255, 255));
        Estrategia_Evaluacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Duracion.setBackground(new java.awt.Color(86, 81, 81));
        Duracion.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Duracion.setForeground(new java.awt.Color(255, 255, 255));
        Duracion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Denominacion.setBackground(new java.awt.Color(86, 81, 81));
        Denominacion.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Denominacion.setForeground(new java.awt.Color(255, 255, 255));
        Denominacion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Denominacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DenominacionActionPerformed(evt);
            }
        });

        Perfil_Docente.setBackground(new java.awt.Color(86, 81, 81));
        Perfil_Docente.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Perfil_Docente.setForeground(new java.awt.Color(255, 255, 255));
        Perfil_Docente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel15.setText("Perfil Docente");

        jLabel16.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel16.setText("Titulo Universitario");
        jLabel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Titulo.setBackground(new java.awt.Color(86, 81, 81));
        Titulo.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });

        Datos.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Datos.setText("jLabel1");

        Enespera.setBackground(new java.awt.Color(86, 81, 81));
        Enespera.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Enespera.setForeground(new java.awt.Color(255, 255, 255));
        Enespera.setText("Poner en Espera");
        Enespera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EnesperaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EnesperaMouseExited(evt);
            }
        });
        Enespera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnesperaActionPerformed(evt);
            }
        });

        Aprobar.setBackground(new java.awt.Color(86, 81, 81));
        Aprobar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Aprobar.setForeground(new java.awt.Color(255, 255, 255));
        Aprobar.setText("Aprobar");
        Aprobar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AprobarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AprobarMouseExited(evt);
            }
        });
        Aprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprobarActionPerformed(evt);
            }
        });

        Rechazar.setBackground(new java.awt.Color(86, 81, 81));
        Rechazar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Rechazar.setForeground(new java.awt.Color(255, 255, 255));
        Rechazar.setText("Rechazar");
        Rechazar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RechazarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RechazarMouseExited(evt);
            }
        });
        Rechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechazarActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(86, 81, 81));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Enviar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        rechazoLabel.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        rechazoLabel.setText("Indique el motivo de rechazo");

        Exigencias.setBackground(new java.awt.Color(86, 81, 81));
        Exigencias.setColumns(20);
        Exigencias.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Exigencias.setForeground(new java.awt.Color(255, 255, 255));
        Exigencias.setLineWrap(true);
        Exigencias.setRows(5);
        Exigencias.setWrapStyleWord(true);
        Exigencias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane4.setViewportView(Exigencias);

        Aprobar2.setBackground(new java.awt.Color(86, 81, 81));
        Aprobar2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        Aprobar2.setForeground(new java.awt.Color(255, 255, 255));
        Aprobar2.setText("Enviar Carta de intesión");
        Aprobar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Aprobar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Aprobar2MouseExited(evt);
            }
        });
        Aprobar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aprobar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(Datos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(Denominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Perfil_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Aprobar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Estructura_Costo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(Cronograma))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(Estructura_Curricular, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(Estrategia_Evaluacion))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(rechazoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Aprobar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Enespera, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Rechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Datos)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Denominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Perfil_Docente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Aprobar2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rechazoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(Duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(Estructura_Costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(Cronograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(Estructura_Curricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Estrategia_Evaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Enespera, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jButton2.setBackground(new java.awt.Color(86, 81, 81));
        jButton2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Atras");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
    setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void DenominacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DenominacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DenominacionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(evt.getSource() == jButton2){
        Denominacion.setText(""); Objetivos.setText(""); Fundamentacion.setText(""); Perfil.setText(""); Perfil_Docente.setText(""); Estructura_Curricular.setText(""); Estrategia_Evaluacion.setText(""); carta.setText(""); Duracion.setText(""); Estructura_Costo.setText(""); Cronograma.setText("");
            CursosView frame= new CursosView();
            frame.setVisible(true);
            this.setVisible(false);
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloActionPerformed

    private void EnesperaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnesperaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EnesperaMouseEntered

    private void EnesperaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnesperaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_EnesperaMouseExited

    private void EnesperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnesperaActionPerformed
                BD_Control DB = BD_Control.getinstancia();
                ArrayList<Proponente> Proponentes= DB.getProponentes();
                Proponente_Control proponente = Proponente_Control.getinstancia();
                String nombreCurso = Denominacion.getText();
                String nombre = proponente.getProponente().getNombre();
                for (Proponente Proponente : Proponentes) {
                    ArrayList<Curso> Cursos = Proponente.getCursos();
                    for(Curso curso : Cursos){
                        if(Proponente.getNombre().equals(nombre) && curso.getFormulario().getDenominacion().equals(nombreCurso)){
                            curso.setEstado(false); DB.guardarTxt();
                           JOptionPane.showMessageDialog(this, "Propuesta de Curso en espera");
                        }
                    }
                    
                }
    }//GEN-LAST:event_EnesperaActionPerformed

    private void AprobarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AprobarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AprobarMouseEntered

    private void AprobarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AprobarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_AprobarMouseExited

    private void AprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprobarActionPerformed
        Aprobar2.setVisible(true); carta.setVisible(true);
        carta.setText("");
        BD_Control DB = BD_Control.getinstancia();
                ArrayList<Proponente> Proponentes= DB.getProponentes();
                Proponente_Control proponente = Proponente_Control.getinstancia();
                String nombreCurso = Denominacion.getText();
                String nombre = proponente.getProponente().getNombre();
                for (Proponente Proponente : Proponentes) {
                    ArrayList<Curso> Cursos = Proponente.getCursos();
                    for(Curso curso : Cursos){
                        if(Proponente.getNombre().equals(nombre) && curso.getFormulario().getDenominacion().equals(nombreCurso)){
                            curso.setEstado(true); DB.guardarTxt();
                           JOptionPane.showMessageDialog(this, "Curso Aprobado");
                        }
                    }
                    
                }
    }//GEN-LAST:event_AprobarActionPerformed

    private void RechazarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechazarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_RechazarMouseEntered

    private void RechazarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RechazarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_RechazarMouseExited

    private void RechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechazarActionPerformed
        Proponente_Control proponente = Proponente_Control.getinstancia();
        JOptionPane.showMessageDialog(this, "Envie la Carta del motivo del Rechazo aquí");
        rechazoLabel.setVisible(true);
        carta.setText("");
        carta.setVisible(true);
        jButton3.setVisible(true);
        Rechazar.setEnabled(false);
    }//GEN-LAST:event_RechazarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String algo = carta.getText();
        if(evt.getSource() == jButton3 ){

            if(!"".equals(carta.getText())) {
                Rechazar.setSelected(false); 
                carta.setVisible(false); 
                jButton3.setVisible(false);
                rechazoLabel.setVisible(false);
                
                
                Factory_Cartas rechazo = new Factory_Cartas_Rechazo();
                rechazo.Subir_Carta(carta.getText());
                
                
                
                JOptionPane.showMessageDialog(this, "Carta Rechazo Enviada Exitosamente!");
            } else {
                JOptionPane.showMessageDialog(this, "No se puede enviar un link vacío");

            }

        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Aprobar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Aprobar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Aprobar2MouseEntered

    private void Aprobar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Aprobar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Aprobar2MouseExited

    private void Aprobar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aprobar2ActionPerformed
         if(!"".equals(carta.getText())){
            
            
            Factory_Cartas intencion = new Factory_Cartas_intencion();
            intencion.Subir_Carta(carta.getText());
                
            
            JOptionPane.showMessageDialog(this, "Carta de Intención Enviada");
            Aprobar2.setEnabled(false);
            carta.setText("");
            carta.setVisible(false);
        }else {
            JOptionPane.showMessageDialog(this, "No se puede enviar una carta vacia");
            
        }
       
    }//GEN-LAST:event_Aprobar2ActionPerformed
    
    private void mostrar_curso(){
    
    Curso_Control curso = Curso_Control.getinstancia();
    Proponente_Control Proponente = Proponente_Control.getinstancia();
    
    Denominacion.setText(curso.getCurso().getFormulario().getDenominacion());
    Duracion.setText(curso.getCurso().getFormulario().getDuracion());
    Objetivos.setText(curso.getCurso().getFormulario().getObjetivos());
    Cronograma.setText(curso.getCurso().getFormulario().getCronograma_De_Ejecucion());
    Fundamentacion.setText(curso.getCurso().getFormulario().getFundamentacion());
    Estrategia_Evaluacion.setText(curso.getCurso().getFormulario().getEstrategias_Evaluacion());
    Estructura_Costo.setText(curso.getCurso().getFormulario().getEstructura_Costo());
    Estructura_Curricular.setText(curso.getCurso().getFormulario().getEstructura_Curricular());
    Exigencias.setText(curso.getCurso().getFormulario().getExigencias_y_Servicios());
    Perfil.setText(curso.getCurso().getFormulario().getPerfiles_I_E());
    Perfil_Docente.setText(curso.getCurso().getFormulario().getPerfil_Docente());
    Titulo.setText(Proponente.getProponente().getTitulo());
    Datos.setText(Proponente.getProponente().getNombre() + " " + " V - " + Proponente.getProponente().getCedula());
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoDetalladoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoDetalladoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoDetalladoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoDetalladoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoDetalladoView().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aprobar;
    private javax.swing.JButton Aprobar2;
    private javax.swing.JTextField Cronograma;
    private javax.swing.JLabel Datos;
    private javax.swing.JTextField Denominacion;
    private javax.swing.JTextField Duracion;
    private javax.swing.JButton Enespera;
    private javax.swing.JTextField Estrategia_Evaluacion;
    private javax.swing.JTextField Estructura_Costo;
    private javax.swing.JTextField Estructura_Curricular;
    private javax.swing.JTextArea Exigencias;
    private javax.swing.JTextArea Fundamentacion;
    private javax.swing.JTextArea Objetivos;
    private javax.swing.JTextField Perfil;
    private javax.swing.JTextField Perfil_Docente;
    private javax.swing.JButton Rechazar;
    private javax.swing.JTextField Titulo;
    private javax.swing.JTextArea carta;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel rechazoLabel;
    // End of variables declaration//GEN-END:variables
}
